<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Debug</title>
    <style>
        @import url("https://fonts.googleapis.com/css?family=Roboto");
        
        body
        {
            background: #212121;
            color: rgba(255, 255, 255, 0.7);

            font-family: "Roboto", "Open Sans", sans-serif;
            font-size: 16px;
        }
        
        .secondary
        {
            color: rgba(255, 255, 255, 0.5);
        }

        details.trace
        {
            margin: 8px 0;
        }
        details.trace > summary
        {
            padding: 4px;

            background: rgba(183, 28, 28, 0.5);

            cursor: pointer;

            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            outline: none;
        }
        details.trace > summary:hover
        {
            background: rgba(198, 40, 40, 0.5);
        }
        details.trace > div.details
        {
            padding: 8px 8px;
        }

        .code
        {
            padding: 16px 4px;
        }
        .dump
        {
            padding: 16px 4px;
        }
    </style>
</head>
<body>

<?php
/**
 * @var string $title
 * @var string $message
 * @var string|null $file_path
 * @var string|null $file_line
 * @var array $traces backtrace
 * @var mixed[] $expressions
 */
?>

<h1><?=$title?></h1>

<h2><?=$message?></h2>

<?php if ($file_path AND $file_line): ?>
<?=$file_path?><br /><br />
<div style="border: 1px dashed rgba(158, 158, 158, 0.25)">
    <?php static::highlight($file_path, $file_line); ?>
</div>
<?php endif; ?>

<?php if($expressions): ?>
<div style="border: 1px dashed rgba(158, 158, 158, 0.25) ; padding: 8px">
    <?php \Ace\dump(...$expressions); ?>
</div>
<?php endif; ?>

<?php foreach ($traces as $trace_key => $trace): ?>
    <details class="trace">
        <summary>
            <?php if (isset($trace['file'])): ?>
                <?=$trace['file']?>
            <?php endif; ?>

            <?php if (isset($trace['class'])): ?>
                <span class="secondary" style="float: right"><?=$trace['class']?><?=$trace['type']?><?=$trace['function']?></span>
            <?php elseif (isset($trace['function'])): ?>
                <span class="secondary" style="float: right"><?=$trace['function']?></span>
            <?php endif; ?>
        </summary>
        <div class="details">
            <?php if (isset($trace['file']) OR isset($trace['line'])): ?>
                <div style="border: 1px dashed rgba(158, 158, 158, 0.25)">
                    <?php static::highlight($trace['file'], $trace['line']); ?>
                </div>
            <?php endif; ?>

            <?php if (isset($trace['args']) AND count($trace['args'])): ?>
                <div style="border: 1px dashed rgba(158, 158, 158, 0.25) ; padding: 8px">
                    <?php \Ace\dump($trace['args']); ?>
                </div>
            <?php endif; ?>
        </div>
    </details>
<?php endforeach; ?>
