<h1>Debug Error <?=$type?></h1>

<h2><?=$errstr?></h2>

<?php if ($errfile): ?>
<?=$errfile?><br /><br />
<div style="border: 1px dashed rgba(158, 158, 158, 0.25)">
    <?php static::highlight($errfile, $errline); ?>
</div>
<?php endif; ?>

<?php if (count($errcontext)): ?>
<div style="border: 1px dashed rgba(158, 158, 158, 0.25)">
    <?php \AceOugi\Dumper::dump($errcontext); ?>
</div>
<?php endif; ?>
