<?php /** @var \Throwable $ex */ ?>

<h1>Debug Exception <?=get_class($ex)?> <?php if ($ex->getCode()) echo '#'.$ex->getCode(); ?></h1>

<h2><?=$ex->getMessage()?></h2>

<?=$ex->getFile()?><br /><br />
<div style="border: 1px dashed rgba(158, 158, 158, 0.25)">
<?php static::highlight($ex->getFile(), $ex->getLine()); ?>
</div>

<?php foreach ($ex->getTrace() as $trace_key => $trace): ?>
<details class="trace">
    <summary>
        <?php if (isset($trace['file'])): ?>
            <?=$trace['file']?>
        <?php endif; ?>

        <?php if (isset($trace['class'])): ?>
            <span class="secondary" style="float: right"><?=$trace['class']?><?=$trace['type']?><?=$trace['function']?></span>
        <?php elseif (isset($trace['function'])): ?>
            <span class="secondary" style="float: right"><?=$trace['function']?></span>
        <?php endif; ?>
    </summary>
    <div class="details">
        <?php if (isset($trace['file']) OR isset($trace['line'])): ?>
        <div style="border: 1px dashed rgba(158, 158, 158, 0.25)">
            <?php static::highlight($trace['file'], $trace['line']); ?>
        </div>
        <?php endif; ?>

        <?php if (isset($trace['args']) AND count($trace['args'])): ?>
        <div style="border: 1px dashed rgba(158, 158, 158, 0.25) ; padding: 8px">
            <?php \AceOugi\Dumper::dump($trace['args']); ?>
        </div>
        <?php endif; ?>
    </div>
</details>
<?php endforeach; ?>
